#!/usr/bin/env ruby

require 'csv'
require 'dotenv'
require 'pony'
require_relative 'msg'
require_relative 'email'

Dotenv.load

csv_file = ENV['CSV'] || 'test.csv'
template_file = ENV['TEMPLATE'] || 'test.txt'
template = File.read(template_file)

Pony.override_options = { :via => :test } if ENV['TEST']

CSV.foreach(csv_file, :headers => :first_row) do |row|
  msg = Msg.new(row, template)
  Email.new(msg).dispatch
end

puts Mail::TestMailer.deliveries if ENV['TEST']
